name: Generate README on Tags Change (Forked PR)

on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme-fork:
    runs-on: ubuntu-latest
    env:
      TITLE: ${{ github.event.pull_request.title }}
    steps:
      - name: Print PR Title
        run: echo "$TITLE"
