name: Generate README on Tags Change (Forked PR)

on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme-fork:
    if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}  # Ensure branch checkout
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create new PR, comment and close original (forked PR)
        env:
          # Use a different token here for fork PRs if needed.
          GITHUB_TOKEN: ${{ secrets.TAGS_YAML_UPDATE_GHA }}
        run: |
          set -e
          cp tags.yaml /tmp/tags.yaml
